export type * from "./contracts/index.js";
export {
  ContextEngineNotImplementedError,
  ContextProjectionError,
  InvestigationRunnerError,
  InvalidInvestigationRequestError,
  createDeterministicInvestigationPlanner,
  createDeterministicInvestigationInterpreter,
  createContextEngineV2,
  createContextProjectionService,
  createInvestigationRunner,
  estimateCanonicalOperationCost,
} from "./application/index.js";
export type {
  ContextEngineServiceDependencies,
  ContextEngineV2,
  ContextProjectionErrorCode,
  ContextProjectionInput,
  ContextProjectionResult,
  ContextProjectionService,
  DeterministicInvestigationPlan,
  DeterministicInvestigationInterpreter,
  DeterministicInvestigationSeed,
  DeterministicInvestigationPlanner,
  DeterministicPlannerPolicy,
  DeterministicPlannerState,
  InvestigationRunner,
  InvestigationRunnerDependencies,
  InvestigationRunnerErrorCode,
  InvestigationRunnerInput,
  InvestigationRunnerResult,
  InvestigationRunnerTraceEvent,
  InvestigationSeedRationale,
  ProjectionDiagnostic,
  ProjectionEntityDecision,
  ProjectionPurpose,
  ProjectionReasonCode,
} from "./application/index.js";
export {
  FactExtractionConflictError,
  CompatibilityComparisonError,
  KnowledgeGraphStoreError,
  LegacyInventorySnapshotError,
  LegacyProjectionError,
  createFactExtractorRegistry,
  createInMemoryKnowledgeGraphStore,
  createLegacyInventorySnapshotPort,
  createLegacyTaskFileSelectionProjection,
  createManifestFactExtractor,
  createTypeScriptJavaScriptFactExtractor,
  createOfflineCompatibilityComparison,
} from "./adapters/index.js";
export type {
  ComparisonOutcome,
  CompatibilityComparisonSummary,
  CompatibilityEvaluationBasis,
  EvidenceComparison,
  KnowledgeGraphStoreErrorCode,
  LegacyInventorySnapshotIssue,
  LegacyInventorySnapshotPortOptions,
  LegacyProjectionDiagnostic,
  LegacyProjectionErrorCode,
  LegacyProjectionExclusion,
  LegacyProjectionFileTrace,
  LegacyProjectionOptions,
  LegacyProjectionResult,
  LegacySelectionSummary,
  LegacyTaskFileSelectionProjection,
  OfflineCompatibilityComparison,
  OfflineCompatibilityComparisonInput,
  SafetyComparison,
  SelectionOverlap,
  V2ProjectionSummary,
} from "./adapters/index.js";
export type {
  ClockPort,
  ExtractionLimitation,
  ExtractionResult,
  ExtractorInput,
  FactExtractorPort,
  FactQuery,
  KnowledgeEdge,
  KnowledgeGraphStorePort,
  KnowledgeGraphBatch,
  KnowledgeTraceExport,
  InvestigationCancellationPort,
  NeighborQuery,
} from "./ports/index.js";
export {
  InvestigationDomainError,
  applyOperationCost,
  calculateInvestigationCoverage,
  canFitOperationCost,
  createContradictionRegistry,
  createEvidenceLedger,
  createHypothesisLedger,
  createInvestigationBudgetState,
  createKnowledgeGapRegistry,
  createStopPolicy,
  detectDeterministicContradictions,
  evaluateClaim,
  evaluateEvidenceRequirement,
  evaluateFindingEligibility,
  snapshotInvestigationBudget,
} from "./domain/index.js";
export type {
  ClaimEvaluation,
  ClaimEvaluationInput,
  ContradictionDetection,
  ContradictionRegistry,
  EvidenceLedger,
  EvidenceRequirementEvaluation,
  EvidenceRequirementEvaluationInput,
  FindingEligibilityEvaluation,
  HypothesisClaimEvaluationInput,
  HypothesisLedger,
  HypothesisReopenInput,
  HypothesisTransitionInput,
  InvestigationCoverageInput,
  InvestigationDomainErrorCode,
  KnowledgeGapRegistry,
  StopDecision,
  StopPolicy,
  StopPolicyState,
} from "./domain/index.js";
