export const TEMPLATES_STUDIO_COPY = {
  en: {
    eyebrow: "Template studio",
    title: "Templates",
    description:
      "Create and review the reusable instructions that shape Task Packs. Built-ins stay protected; your own items remain local and editable.",
    refresh: "Refresh",
    refreshing: "Refreshing…",
    create: "Create",
    createTemplate: "New template",
    createProfile: "New profile",
    createRule: "New rule",
    createCriteria: "New criteria set",
    summary: {
      templates: "Templates",
      custom: "Custom",
      protected: "Protected",
      profiles: "Profiles",
    },
    tabs: {
      templates: "Templates",
      templatesCaption: "Task Pack structure",
      profiles: "Profiles",
      profilesCaption: "Reusable rule bundles",
      rules: "Rules",
      rulesCaption: "Focused instructions",
      criteria: "Criteria",
      criteriaCaption: "Completion checks",
    },
    searchPlaceholder: "Search the current collection…",
    filterByTask: "Task type",
    filterByCategory: "Rule category",
    allTaskTypes: "All task types",
    allAgents: "All agent formats",
    allCategories: "All categories",
    library: "Library",
    collections: "Collections",
    allItems: "All items",
    customItems: "My items",
    builtinItems: "Built-in",
    agents: "Agent formats",
    itemCount: "{{count}} items",
    customCount: "{{count}} custom",
    builtinCount: "{{count}} built-in",
    noDescription: "No description yet.",
    builtIn: "Built-in",
    custom: "Custom",
    protected: "Protected",
    editable: "Editable",
    updated: "Updated {{date}}",
    created: "Created {{date}}",
    open: "Open",
    actions: "Actions",
    duplicate: "Create copy",
    edit: "Edit",
    delete: "Delete",
    copyId: "Copy ID",
    copied: "Copied",
    emptyTitle: "Nothing matches this view",
    emptyDescription:
      "Change the filters or create a custom item for this collection.",
    emptyCustomTitle: "Create your first local item",
    emptyCustomDescription:
      "Start from a protected built-in item or create a clean structure from scratch.",
    inspector: {
      preview: "Inspector",
      selectedTemplate: "Selected template",
      selectedProfile: "Selected profile",
      selectedRule: "Selected rule",
      selectedCriteria: "Selected criteria set",
      selectTitle: "Select an item to inspect",
      selectDescription:
        "The inspector shows structure, usage, variables and safe actions without opening another page.",
      target: "Target agent",
      taskType: "Task type",
      source: "Source",
      variables: "Variables",
      sections: "Sections",
      content: "Template content",
      structure: "Structure",
      rules: "Enabled rules",
      customRules: "Profile rules",
      criteria: "Checks",
      usedBy: "Used by profiles",
      none: "None",
      acceptancePreset: "Acceptance preset",
      safeNotice:
        "Built-in items cannot be edited or deleted. Create a local copy before changing them.",
    },
    marketplace: {
      eyebrow: "ContextForge Workshop",
      title: "Community templates will live on the website",
      description:
        "A future website module will let creators publish, review and install templates through an explicit account-linked transfer. Local items will never upload automatically.",
      planned: "Planned",
      openWebsite: "Open website",
      syncCatalog: "Sync catalog",
      publish: "Publish template",
      localFirst: "Explicit transfer only",
    },
    editor: {
      createEyebrow: "Create local item",
      editEyebrow: "Edit local item",
      copyEyebrow: "Customize protected copy",
      templateCreate: "New prompt template",
      templateEdit: "Edit prompt template",
      profileCreate: "New rule profile",
      profileEdit: "Edit rule profile",
      ruleCreate: "New rule",
      ruleEdit: "Edit rule",
      criteriaCreate: "New criteria set",
      criteriaEdit: "Edit criteria set",
      close: "Close panel",
      reset: "Reset",
      save: "Save",
      saving: "Saving…",
      steps: {
        setup: "Setup",
        setupCaption: "Name and scope",
        structure: "Structure",
        structureCaption: "Rules and content",
        preview: "Preview",
        previewCaption: "Review before saving",
      },
      name: "Name",
      nameTemplatePlaceholder: "Focused UI implementation",
      nameProfilePlaceholder: "Safe UI profile",
      nameRulePlaceholder: "Preserve route behaviour",
      nameCriteriaPlaceholder: "UI completion checks",
      description: "Short description",
      descriptionPlaceholder: "Explain when this item should be selected.",
      taskType: "Task type",
      targetTool: "Target agent",
      category: "Rule category",
      templateContent: "Template body",
      templateHint:
        "Use Markdown and ContextForge variables. Unknown variables render as empty strings.",
      ruleContent: "Instruction",
      ruleContentHint: "Write one clear, testable instruction.",
      criteria: "Completion checks",
      criteriaHint: "One check per line.",
      enabledRules: "Enabled rules",
      enabledRulesHint: "Profiles can combine protected and custom rules.",
      acceptancePreset: "Acceptance preset",
      noPreset: "No preset",
      noPresetDescription: "Use only profile rules",
      customRules: "Additional profile rules",
      customRulesHint: "One rule per line.",
      characters: "{{count}} characters",
      lines: "{{count}} lines",
      variableCount: "{{count}} variables",
      sectionCount: "{{count}} sections",
      reviewTitle: "Ready to save locally",
      reviewDescription:
        "Review the structure below. Saving does not send data to the website or an AI provider.",
      localOnly: "Saved on this device",
      protectedSource: "Source built-in remains unchanged",
      invalidName: "Use at least 2 characters for the name.",
      invalidTemplate: "Template content must contain at least 20 characters.",
      invalidRule: "Rule content must contain at least 10 characters.",
      invalidCriteria: "Add at least one completion check.",
      saveFailed: "Could not save this item.",
    },
    deleteDialog: {
      eyebrow: "Delete local item",
      title: "Delete “{{name}}”?",
      description:
        "This removes the custom item from the local catalog. Protected built-ins are never deleted.",
      cancel: "Cancel",
      confirm: "Delete item",
      deleting: "Deleting…",
      failed: "Could not delete this item.",
      dependency:
        "This item is still used by one or more profiles. Remove that reference first.",
    },
    status: {
      loading: "Loading the local catalog…",
      ready: "Catalog ready",
      loadFailed: "Could not load the template catalog.",
      saved: "Saved locally",
      deleted: "Deleted from the local catalog",
      copyReady: "A custom copy is ready to edit",
    },
    taskTypes: {
      general: "General",
      ui: "UI / UX",
      backend: "Backend",
      fullstack: "Fullstack",
      build: "Build",
      bugfix: "Bug fix",
      refactor: "Refactor",
      docs: "Documentation",
      tests: "Tests",
    },
    categories: {
      general: "General",
      ui: "UI",
      backend: "Backend",
      bugfix: "Bug fix",
      refactor: "Refactor",
      docs: "Documentation",
      tests: "Tests",
      assets: "Assets",
      verification: "Verification",
    },
  },
  ru: {
    eyebrow: "Студия шаблонов",
    title: "Шаблоны",
    description:
      "Создавайте и проверяйте повторно используемые инструкции, которые формируют пакеты задач. Встроенные элементы защищены, пользовательские остаются локальными и доступны для редактирования.",
    refresh: "Обновить",
    refreshing: "Обновление…",
    create: "Создать",
    createTemplate: "Новый шаблон",
    createProfile: "Новый профиль",
    createRule: "Новое правило",
    createCriteria: "Набор критериев",
    summary: {
      templates: "Шаблоны",
      custom: "Пользовательские",
      protected: "Защищённые",
      profiles: "Профили",
    },
    tabs: {
      templates: "Шаблоны",
      templatesCaption: "Структура пакета задач",
      profiles: "Профили",
      profilesCaption: "Наборы правил",
      rules: "Правила",
      rulesCaption: "Точные инструкции",
      criteria: "Критерии",
      criteriaCaption: "Проверки результата",
    },
    searchPlaceholder: "Поиск в текущем разделе…",
    filterByTask: "Тип задачи",
    filterByCategory: "Категория правила",
    allTaskTypes: "Все типы задач",
    allAgents: "Все форматы",
    allCategories: "Все категории",
    library: "Библиотека",
    collections: "Коллекции",
    allItems: "Все элементы",
    customItems: "Мои элементы",
    builtinItems: "Встроенные",
    agents: "Форматы агентов",
    itemCount: "Элементов: {{count}}",
    customCount: "Пользовательских: {{count}}",
    builtinCount: "Встроенных: {{count}}",
    noDescription: "Описание пока не добавлено.",
    builtIn: "Встроенный",
    custom: "Пользовательский",
    protected: "Защищён",
    editable: "Можно изменить",
    updated: "Обновлён {{date}}",
    created: "Создан {{date}}",
    open: "Открыть",
    actions: "Действия",
    duplicate: "Создать копию",
    edit: "Редактировать",
    delete: "Удалить",
    copyId: "Скопировать ID",
    copied: "Скопировано",
    emptyTitle: "В этом представлении ничего нет",
    emptyDescription:
      "Измените фильтры или создайте пользовательский элемент для этой коллекции.",
    emptyCustomTitle: "Создайте первый локальный элемент",
    emptyCustomDescription:
      "Возьмите защищённый встроенный элемент за основу или начните с чистой структуры.",
    inspector: {
      preview: "Инспектор",
      selectedTemplate: "Выбранный шаблон",
      selectedProfile: "Выбранный профиль",
      selectedRule: "Выбранное правило",
      selectedCriteria: "Выбранный набор критериев",
      selectTitle: "Выберите элемент для просмотра",
      selectDescription:
        "Инспектор показывает структуру, использование, переменные и безопасные действия без перехода на другую страницу.",
      target: "Целевой агент",
      taskType: "Тип задачи",
      source: "Источник",
      variables: "Переменные",
      sections: "Разделы",
      content: "Содержимое шаблона",
      structure: "Структура",
      rules: "Включённые правила",
      customRules: "Правила профиля",
      criteria: "Проверки",
      usedBy: "Используется профилями",
      none: "Нет",
      acceptancePreset: "Набор критериев",
      safeNotice:
        "Встроенные элементы нельзя изменить или удалить. Сначала создайте локальную копию.",
    },
    marketplace: {
      eyebrow: "Мастерская ContextForge",
      title: "Пользовательские шаблоны появятся на сайте",
      description:
        "Будущий модуль сайта позволит авторам публиковать, оценивать и устанавливать шаблоны через явную передачу между аккаунтом и Desktop. Локальные элементы никогда не загружаются автоматически.",
      planned: "В планах",
      openWebsite: "Открыть сайт",
      syncCatalog: "Синхронизировать каталог",
      publish: "Опубликовать шаблон",
      localFirst: "Только явная передача",
    },
    editor: {
      createEyebrow: "Создание локального элемента",
      editEyebrow: "Редактирование локального элемента",
      copyEyebrow: "Настройка защищённой копии",
      templateCreate: "Новый шаблон промпта",
      templateEdit: "Редактирование шаблона",
      profileCreate: "Новый профиль правил",
      profileEdit: "Редактирование профиля",
      ruleCreate: "Новое правило",
      ruleEdit: "Редактирование правила",
      criteriaCreate: "Новый набор критериев",
      criteriaEdit: "Редактирование критериев",
      close: "Закрыть панель",
      reset: "Сбросить",
      save: "Сохранить",
      saving: "Сохранение…",
      steps: {
        setup: "Основное",
        setupCaption: "Название и область",
        structure: "Структура",
        structureCaption: "Правила и содержимое",
        preview: "Проверка",
        previewCaption: "Просмотр перед сохранением",
      },
      name: "Название",
      nameTemplatePlaceholder: "Точная реализация интерфейса",
      nameProfilePlaceholder: "Безопасный UI-профиль",
      nameRulePlaceholder: "Сохранить поведение маршрута",
      nameCriteriaPlaceholder: "Проверки готовности UI",
      description: "Краткое описание",
      descriptionPlaceholder: "Объясните, когда следует выбирать этот элемент.",
      taskType: "Тип задачи",
      targetTool: "Целевой агент",
      category: "Категория правила",
      templateContent: "Тело шаблона",
      templateHint:
        "Используйте Markdown и переменные ContextForge. Неизвестные переменные заменяются пустой строкой.",
      ruleContent: "Инструкция",
      ruleContentHint: "Напишите одну понятную и проверяемую инструкцию.",
      criteria: "Проверки завершения",
      criteriaHint: "Одна проверка на строку.",
      enabledRules: "Включённые правила",
      enabledRulesHint: "Профили могут объединять встроенные и пользовательские правила.",
      acceptancePreset: "Набор критериев",
      noPreset: "Без набора",
      noPresetDescription: "Использовать только правила профиля",
      customRules: "Дополнительные правила профиля",
      customRulesHint: "Одно правило на строку.",
      characters: "Символов: {{count}}",
      lines: "Строк: {{count}}",
      variableCount: "Переменных: {{count}}",
      sectionCount: "Разделов: {{count}}",
      reviewTitle: "Готово к локальному сохранению",
      reviewDescription:
        "Проверьте структуру ниже. Сохранение не отправляет данные на сайт или AI-провайдеру.",
      localOnly: "Сохраняется на этом устройстве",
      protectedSource: "Исходный встроенный элемент не изменится",
      invalidName: "Название должно содержать не менее 2 символов.",
      invalidTemplate: "Содержимое шаблона должно содержать не менее 20 символов.",
      invalidRule: "Инструкция должна содержать не менее 10 символов.",
      invalidCriteria: "Добавьте хотя бы одну проверку завершения.",
      saveFailed: "Не удалось сохранить элемент.",
    },
    deleteDialog: {
      eyebrow: "Удаление локального элемента",
      title: "Удалить «{{name}}»?",
      description:
        "Элемент будет удалён из локального каталога. Защищённые встроенные элементы никогда не удаляются.",
      cancel: "Отмена",
      confirm: "Удалить элемент",
      deleting: "Удаление…",
      failed: "Не удалось удалить элемент.",
      dependency:
        "Элемент всё ещё используется одним или несколькими профилями. Сначала удалите эту связь.",
    },
    status: {
      loading: "Загрузка локального каталога…",
      ready: "Каталог готов",
      loadFailed: "Не удалось загрузить каталог шаблонов.",
      saved: "Сохранено локально",
      deleted: "Удалено из локального каталога",
      copyReady: "Пользовательская копия готова к редактированию",
    },
    taskTypes: {
      general: "Общая",
      ui: "UI / UX",
      backend: "Backend",
      fullstack: "Fullstack",
      build: "Сборка",
      bugfix: "Исправление ошибки",
      refactor: "Рефакторинг",
      docs: "Документация",
      tests: "Тесты",
    },
    categories: {
      general: "Общие",
      ui: "UI",
      backend: "Backend",
      bugfix: "Исправление ошибки",
      refactor: "Рефакторинг",
      docs: "Документация",
      tests: "Тесты",
      assets: "Ресурсы",
      verification: "Проверка",
    },
  },
} as const;

export type TemplatesStudioCopy =
  (typeof TEMPLATES_STUDIO_COPY)[keyof typeof TEMPLATES_STUDIO_COPY];
